import keyMirror from 'key-mirror'

export const COORDINATES = {
    DEFAULT_LATITUDE_DELTA: 44.976073,
    DEFAULT_LONGITUDE_DELTA: -93.272293
}

export const DIMENSIONS = {
    FOOTER_HEIGHT: 75,
    NAVIGATION_BAR_HEIGHT: 80
}

export const ERROR_CODES = {
    INVALID_SSN: 'invalid.ssn',
    INVALID_EMAIL: 'invalid.email',
    INVALID_LOGIN: 'invalid.login'
}

export const SERVER_ERROR_CODES = {
    NO_CONNECTION: 'no.connection',
    CONNECTION_ABORTED: 'ECONNABORTED',
    INTERNAL_SERVER_ERROR: 'internal.server.error',
    SERVER_IS_NOT_AVAILABLE: 'server.is.not.available',
    NO_CONNECTION_OR_SERVER_IS_NOT_AVAILABLE: 'no.connection.or.server.is.not.available',

    INVALID_TOKEN: 'token.invalid',
    INVALID_PASSWORD: 'invalid.password',
    INVALID_LOGIN: 'invalid.login',
    INVALID_COMPANY_ID: 'invalid.company.id',

    NO_PHYSICIAN_FOUND: 'physician.not.found',
    NO_PATIENT_INFO_FOUND: 'patient.info.not.found',
    NO_PATIENTS_FOUND: 'no.associated.patients.found',

    NO_PHONE_FOR_REGISTRATION: 'no.phone.for.registration',
    NO_EMAIL_FOR_REGISTRATION: 'no.email.for.registration',
    NO_PHONE_AND_EMAIL_FOR_REGISTRATION: 'no.phone.and.email.for.registration',

    UNAUTHORIZED: 'auth.authorized',
    BAD_CREDENTIALS: 'auth.bad.credentials',
    EXPIRED_CREDENTIALS: 'auth.credentials.expired',

    ACCOUNT_LOCKED: 'auth.account.locked',
    ACCOUNT_INACTIVE: 'auth.account.inactive',
    ACCOUNT_NOT_FOUND: 'auth.account.not.found',

    COMING_SOON: 'coming.soon'
}

export let VALIDATION_ERROR_TEXTS = {
    EMPTY_FIELD: 'Please fill in the required field',
    LENGTH_MINIMUM: 'Please enter at least $0 characters',
    LENGTH_MAXIMUM: 'Please enter not more than $0 characters',
    LENGTH_EQUAL: 'Please enter $0 characters',
    EMAIL_FORMAT: 'Please enter a valid email address',
    PHONE_FORMAT: 'Please enter a valid phone number',
    FAX_FORMAT: 'Please enter a valid fax number',
    NUMBER_FORMAT: 'Only digits are allowed',
    ZIP_CODE_FORMAT: 'The specified US zip code is not valid.',
    NUMBER_FORMAT_SPECIFIC: 'Please enter only $0 digits',
    NUMBER_LENGTH_MINIMUM: 'Please enter at least $0 digit',
    NUMBER_LENGTH_MAXIMUM: 'Please enter not more than $0 digit',
    CONFIRM_PASSWORD_MATCH: 'The passwords you entered do not match',
    PASSWORD_COMPLEXITY: `The password you entered doesn't meet complexity requirements.`,
    FILE_SIZE: 'Please not upload file more than $0 MB',
    FILE_FORMAT: 'This file type is not allowed',
    NON_UNIQ_SHORT: 'The $0 with $1 entered already exists.',
    NON_UNIQ: 'The $0 with $1 entered already exists in the system.'
}

export const ENTITY_TYPES = keyMirror({
    EVENT: null,
    PHONE: null,
    PERSON: null,
    CLIENT: null,
    ADDRESS: null,
    LOCATION: null,
    CARE_MEMBER: null,
    PHYSICIAN_PROFESSIONAL: null,
    DRIVER_LICENCE_NUMBER: null
})

export let MAX_FILE_NAME_LENGTH = 120

export let ALLOWED_FILE_FORMATS = keyMirror({
    DOC: null,
    DOCX: null,
    PDF: null,
    XLS: null,
    XLSX: null,
    TXT: null,
    XML: null,
    JPG: null,
    PJPG: null,
    PNG: null,
    GIF: null,
    OTHER: null
})

export let FILE_SIZE_FORMATS = keyMirror({
    BYTE: null,
    KB: null,
    MB: null,
    GB: null,
})

export let SYSTEM_ROLES = {
    CASE_MANAGER: 'ROLE_CASE_MANAGER',
    CARE_COORDINATOR: 'ROLE_CARE_COORDINATOR',
    PARENT_GUARDIAN: 'ROLE_PARENT_GUARDIAN',
    PERSON_RECEIVING_SERVICES: 'ROLE_PERSON_RECEIVING_SERVICES',
    PRIMARY_PHYSICIAN: 'ROLE_PRIMARY_PHYSICIAN',
    BEHAVIORAL_HEALTH: 'ROLE_BEHAVIORAL_HEALTH',
    COMMUNITY_MEMBERS: 'ROLE_COMMUNITY_MEMBERS',
    SERVICE_PROVIDER: 'ROLE_SERVICE_PROVIDER',
    ADMINISTRATOR: 'ROLE_ADMINISTRATOR',
    SUPER_ADMINISTRATOR: 'ROLE_SUPER_ADMINISTRATOR',
    COMMUNITY_ADMINISTRATOR: 'ROLE_COMMUNITY_ADMINISTRATOR',
    NOTIFY_USER: 'ROLE_NOTIFY_USER',
    PHARMACIST: 'ROLE_PHARMACIST',
    NURSE: 'ROLE_NURSE'
}

export let PROFESSIONAL_SYSTEM_ROLES = [
    SYSTEM_ROLES.CASE_MANAGER,
    SYSTEM_ROLES.CARE_COORDINATOR,
    SYSTEM_ROLES.PHARMACIST,
    SYSTEM_ROLES.NURSE,
    SYSTEM_ROLES.PRIMARY_PHYSICIAN,
    SYSTEM_ROLES.BEHAVIORAL_HEALTH,
    SYSTEM_ROLES.COMMUNITY_MEMBERS,
    SYSTEM_ROLES.SERVICE_PROVIDER,
    SYSTEM_ROLES.ADMINISTRATOR,
    SYSTEM_ROLES.COMMUNITY_ADMINISTRATOR,
    SYSTEM_ROLES.SUPER_ADMINISTRATOR
]

export let PASSWORD_VALIDATION_TYPES = keyMirror({
    DIGIT: null,
    MIN_CHARACTERS: null,
    UPPERCASE_LETTER: null,
    LOWERCASE_LETTER: null,
    SPECIAL_CHARACTERS: null,
})

export let PASSWORD_VALIDATIONS = {
    [PASSWORD_VALIDATION_TYPES.DIGIT]: '.*[0-9]',
    [PASSWORD_VALIDATION_TYPES.SPECIAL_CHARACTERS]: '.*\\W',
    [PASSWORD_VALIDATION_TYPES.UPPERCASE_LETTER]: '.*[A-Z]',
    [PASSWORD_VALIDATION_TYPES.LOWERCASE_LETTER]: '.*[a-z]',
}

export let ALLOWED_FILE_FORMAT_MIME_TYPES = {
    [ALLOWED_FILE_FORMATS.DOC]: 'application/msword',
    [ALLOWED_FILE_FORMATS.DOCX]: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    [ALLOWED_FILE_FORMATS.PDF]: 'application/pdf',
    [ALLOWED_FILE_FORMATS.XLS]: 'application/vnd.ms-excel',
    [ALLOWED_FILE_FORMATS.XLSX]: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    [ALLOWED_FILE_FORMATS.TXT]: 'text/plain',
    [ALLOWED_FILE_FORMATS.XML]: 'text/xml',
    [ALLOWED_FILE_FORMATS.JPG]: 'image/jpeg',
    [ALLOWED_FILE_FORMATS.PJPG]: 'image/pjpeg',
    [ALLOWED_FILE_FORMATS.PNG]: 'image/png',
    [ALLOWED_FILE_FORMATS.GIF]: 'image/gif',
    [ALLOWED_FILE_FORMATS.OTHER]: null
}

export const PAGINATION = { FIRST_PAGE: 1, MAX_SIZE: 0x7fffffff }

/**
 * @name PAGES
 * */
export const PAGES = keyMirror({
    DASHBOARD: null,
    CLIENTS: null,
    EVENTS: null,
    SCHEDULING: null,
    REPORTS: null,
    ADMIN: null,
    ORGANIZATIONS: null,
    ORGANIZATION_DETAILS: null,
    COMMUNITY_DETAILS: null,
    CONTACTS: null,
    ADMIN_CLIENTS: null,
    SUGGESTED_MATCHES: null,
    MANUAL_MATCHING: null
})

export const AUTH_REQUEST_TYPES = keyMirror({
    INVITATION: null,
    RESET_PASSWORD: null
})

export const CONTACT_STATUS_TYPES = keyMirror({
    ACTIVE: null,
    PENDING: null,
    EXPIRED: null,
    INACTIVE: null,
})

export const ASSESSMENT_TYPES = keyMirror({
    COMPREHENSIVE: null,
    GAD7: null,
    PHQ9: null
})

export const ASSESSMENT_STATUSES = keyMirror({
    IN_PROCESS: null,
    INACTIVE: null,
    COMPLETED: null
})

export const GAD7_SCALE = [
    { score: '0-4', severityName: 'NO', severityTitle: 'No', comments: 'No actions required' },
    { score: '5-9', severityName: 'MILD', severityTitle: 'Mild', comments: 'Monitor' },
    {
        score: '10-14',
        severityName: 'MODERATE',
        severityTitle: 'Moderate',
        comments: 'Possible clinically signification'
    },
    { score: '15-24', severityName: 'SEVERE', severityTitle: 'Severe', comments: 'Active treatment probably warranted' }
]

export const PHQ9_SCALE = [
    {
        score: '0-4',
        severityName: 'MINIMAL_OR_NONE',
        severityTitle: 'Minimal or none',
        comments: 'Monitor; may not require treatment'
    },
    {
        score: '5-9',
        severityName: 'MILD',
        severityTitle: 'Mild',
        comments: 'Use clinical judgment (symptom duration, functional impairment) to determine necessity of treatment'
    },
    {
        score: '10-14',
        severityName: 'MODERATE',
        severityTitle: 'Moderate',
        comments: 'Use clinical judgment (symptom duration, functional impairment) to determine necessity of treatment'
    },
    {
        score: '15-19',
        severityName: 'MODERATELY_SEVERE',
        severityTitle: 'Moderately severe',
        comments: 'Warrants active treatment with psychotherapy, medications, or combination'
    },
    {
        score: '20-27',
        severityName: 'SEVERE',
        severityTitle: 'Severe',
        comments: 'Warrants active treatment with psychotherapy, medications, or combination'
    },
]

export const ALERT_TYPES = keyMirror({
    ACTIVE_ALERT: null,
    SYSTEM_ALERT: null,
})

export const ALERT_STATUS_TYPES = keyMirror({
    CLOSED: null,
    UNTAKEN: null,
})

export const COMMUNITY_ITEMS = keyMirror({
    ADD_ZONE: null,
    ADD_HANDSET: null,
    ADD_LOCATION: null,
})

export const DASHBOARD_TYPES = keyMirror({
    CASELOAD: null,
    APPOINTMENT: null,
    RECENT_EVENT: null,
    RECENT_NOTE: null,
})

/**
 * @name ACTION_TYPES
 * */
export const ACTION_TYPES = keyMirror({
    CLEAR_ERROR: null,
    CHANGE_ERROR: null,

    CLEAR_ALL_AUTH_DATA: null,

    VALIDATE_TOKEN_REQUEST: null,
    VALIDATE_TOKEN_SUCCESS: null,
    VALIDATE_TOKEN_FAILURE: null,

    REMOVE_TOKEN_REQUEST: null,
    REMOVE_TOKEN_SUCCESS: null,

    CLEAR_LOGIN_FORM: null,
    CLEAR_LOGIN_FORM_ERROR: null,
    CLEAR_LOGIN_FORM_FIELD_ERROR: null,
    CHANGE_LOGIN_FORM_FIELD: null,
    CHANGE_LOGIN_FORM_FIELDS: null,
    VALIDATE_LOGIN_FORM: null,

    CLEAR_RESET_PASSWORD_FORM: null,
    CLEAR_RESET_PASSWORD_FORM_ERROR: null,
    CLEAR_RESET_PASSWORD_FORM_FIELD_ERROR: null,
    CHANGE_RESET_PASSWORD_FORM_FIELD: null,
    CHANGE_RESET_PASSWORD_FORM_FIELDS: null,
    VALIDATE_RESET_PASSWORD_FORM: null,
    RESET_PASSWORD_REQUEST: null,
    RESET_PASSWORD_SUCCESS: null,
    RESET_PASSWORD_FAILURE: null,

    CLEAR_NEW_PASSWORD_FORM: null,
    CLEAR_NEW_PASSWORD_FORM_ERROR: null,
    CLEAR_NEW_PASSWORD_FORM_FIELD_ERROR: null,
    CHANGE_NEW_PASSWORD_FORM_FIELD: null,
    CHANGE_NEW_PASSWORD_FORM_FIELDS: null,
    VALIDATE_NEW_PASSWORD_FORM: null,
    NEW_PASSWORD_REQUEST: null,
    NEW_PASSWORD_SUCCESS: null,
    NEW_PASSWORD_FAILURE: null,

    CLEAR_OLD_PASSWORD_FORM: null,
    CLEAR_OLD_PASSWORD_FORM_ERROR: null,
    CLEAR_OLD_PASSWORD_FORM_FIELD_ERROR: null,
    CHANGE_OLD_PASSWORD_FORM_FIELD: null,
    CHANGE_OLD_PASSWORD_FORM_FIELDS: null,
    VALIDATE_OLD_PASSWORD_FORM: null,
    OLD_PASSWORD_REQUEST: null,
    OLD_PASSWORD_SUCCESS: null,
    OLD_PASSWORD_FAILURE: null,

    CLEAR_CREATE_PASSWORD_FORM: null,
    CLEAR_CREATE_PASSWORD_FORM_ERROR: null,
    CLEAR_CREATE_PASSWORD_FORM_FIELD_ERROR: null,
    CHANGE_CREATE_PASSWORD_FORM_FIELD: null,
    CHANGE_CREATE_PASSWORD_FORM_FIELDS: null,
    VALIDATE_CREATE_PASSWORD_FORM: null,
    CREATE_PASSWORD_REQUEST: null,
    CREATE_PASSWORD_SUCCESS: null,
    CREATE_PASSWORD_FAILURE: null,
    DECLINE_INVITATION_REQUEST: null,
    DECLINE_INVITATION_SUCCESS: null,
    DECLINE_INVITATION_FAILURE: null,

    CLEAR_COMPLEXITY_RULES: null,
    CLEAR_COMPLEXITY_RULES_ERROR: null,
    LOAD_COMPLEXITY_RULES_REQUEST: null,
    LOAD_COMPLEXITY_RULES_SUCCESS: null,
    LOAD_COMPLEXITY_RULES_FAILURE: null,

    CLEAR_VALIDATE_PASSWORD_TOKEN: null,
    CLEAR_VALIDATE_PASSWORD_TOKEN_ERROR: null,
    LOAD_VALIDATE_PASSWORD_TOKEN_REQUEST: null,
    LOAD_VALIDATE_PASSWORD_TOKEN_SUCCESS: null,
    LOAD_VALIDATE_PASSWORD_TOKEN_FAILURE: null,

    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,
    CLEAR_LOGIN_ERROR: null,
    RESTORE_LOGGED_IN_USER: null,

    CLEAR_SESSION_ERROR: null,

    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,
    CLEAR_LOGOUT_ERROR: null,

    CLEAR_ACTIVE_ALERT_LIST_ERROR: null,

    CLEAR_ACTIVE_ALERT_LIST: null,

    LOAD_ACTIVE_ALERT_LIST_REQUEST: null,
    LOAD_ACTIVE_ALERT_LIST_SUCCESS: null,
    LOAD_ACTIVE_ALERT_LIST_FAILURE: null,

    CLEAR_ACTIVE_ALERT_HISTORY_ERROR: null,

    CLEAR_ACTIVE_ALERT_HISTORY: null,

    LOAD_ACTIVE_ALERT_HISTORY_REQUEST: null,
    LOAD_ACTIVE_ALERT_HISTORY_SUCCESS: null,
    LOAD_ACTIVE_ALERT_HISTORY_FAILURE: null,

    CLEAR_ACTIVE_ALERT_COUNT: null,
    CLEAR_ACTIVE_ALERT_COUNT_ERROR: null,
    LOAD_ACTIVE_ALERT_COUNT_REQUEST: null,
    LOAD_ACTIVE_ALERT_COUNT_SUCCESS: null,
    LOAD_ACTIVE_ALERT_COUNT_FAILURE: null,

    CLEAR_SYSTEM_ALERT_LIST_ERROR: null,
    CLEAR_SYSTEM_ALERT_LIST: null,
    LOAD_SYSTEM_ALERT_LIST_REQUEST: null,
    LOAD_SYSTEM_ALERT_LIST_SUCCESS: null,
    LOAD_SYSTEM_ALERT_LIST_FAILURE: null,

    CLEAR_SYSTEM_ALERT_HISTORY_ERROR: null,

    CLEAR_SYSTEM_ALERT_HISTORY: null,

    LOAD_SYSTEM_ALERT_HISTORY_REQUEST: null,
    LOAD_SYSTEM_ALERT_HISTORY_SUCCESS: null,
    LOAD_SYSTEM_ALERT_HISTORY_FAILURE: null,

    CLEAR_SYSTEM_ALERT_COUNT: null,
    CLEAR_SYSTEM_ALERT_COUNT_ERROR: null,
    LOAD_SYSTEM_ALERT_COUNT_REQUEST: null,
    LOAD_SYSTEM_ALERT_COUNT_SUCCESS: null,
    LOAD_SYSTEM_ALERT_COUNT_FAILURE: null,

    CLEAR_ORGANIZATION_LIST_ERROR: null,
    CLEAR_ORGANIZATION_LIST: null,
    CLEAR_ORGANIZATION_LIST_FILTER: null,
    CHANGE_ORGANIZATION_LIST_FILTER_FIELD: null,
    CHANGE_ORGANIZATION_LIST_SORTING: null,
    LOAD_ORGANIZATION_LIST_REQUEST: null,
    LOAD_ORGANIZATION_LIST_SUCCESS: null,
    LOAD_ORGANIZATION_LIST_FAILURE: null,

    CLEAR_ORGANIZATION_HISTORY_ERROR: null,

    CLEAR_ORGANIZATION_HISTORY: null,

    LOAD_ORGANIZATION_HISTORY_REQUEST: null,
    LOAD_ORGANIZATION_HISTORY_SUCCESS: null,
    LOAD_ORGANIZATION_HISTORY_FAILURE: null,

    CLEAR_ORGANIZATION_COUNT: null,
    CLEAR_ORGANIZATION_COUNT_ERROR: null,
    LOAD_ORGANIZATION_COUNT_REQUEST: null,
    LOAD_ORGANIZATION_COUNT_SUCCESS: null,
    LOAD_ORGANIZATION_COUNT_FAILURE: null,

    CLEAR_CAN_ADD_ORGANIZATION: null,
    CLEAR_CAN_ADD_ORGANIZATION_ERROR: null,
    LOAD_CAN_ADD_ORGANIZATION_REQUEST: null,
    LOAD_CAN_ADD_ORGANIZATION_SUCCESS: null,
    LOAD_CAN_ADD_ORGANIZATION_FAILURE: null,

    CLEAR_ORGANIZATION_DETAILS: null,
    CLEAR_ORGANIZATION_DETAILS_ERROR: null,
    LOAD_ORGANIZATION_DETAILS_REQUEST: null,
    LOAD_ORGANIZATION_DETAILS_SUCCESS: null,
    LOAD_ORGANIZATION_DETAILS_FAILURE: null,

    DOWNLOAD_ORGANIZATION_LOGO_REQUEST: null,
    DOWNLOAD_ORGANIZATION_LOGO_SUCCESS: null,
    DOWNLOAD_ORGANIZATION_LOGO_FAILURE: null,

    LOAD_ORGANIZATION_FORM_DATA_REQUEST: null,
    LOAD_ORGANIZATION_FORM_DATA_SUCCESS: null,
    LOAD_ORGANIZATION_FORM_DATA_FAILURE: null,

    CLEAR_ORGANIZATION_FORM: null,
    CLEAR_ORGANIZATION_FORM_ERROR: null,
    CLEAR_ORGANIZATION_FORM_FIELD_ERROR: null,

    VALIDATE_ORGANIZATION_DATA_UNIQ_REQUEST: null,
    VALIDATE_ORGANIZATION_DATA_UNIQ_SUCCESS: null,
    VALIDATE_ORGANIZATION_DATA_UNIQ_FAILURE: null,

    CHANGE_ORGANIZATION_FORM_TAB: null,

    CHANGE_ORGANIZATION_FORM_FIELD: null,
    CHANGE_ORGANIZATION_FORM_FIELDS: null,
    CHANGE_ORGANIZATION_FORM_MARKET_PLACE_FIELD: null,

    VALIDATE_ORGANIZATION_FORM: null,
    VALIDATE_ORGANIZATION_FORM_LEGAL_INFO: null,
    VALIDATE_ORGANIZATION_FORM_MARKETPLACE: null,
    VALIDATE_ORGANIZATION_FORM_AFFILIATE_RELATIONSHIP: null,

    SAVE_ORGANIZATION_REQUEST: null,
    SAVE_ORGANIZATION_SUCCESS: null,
    SAVE_ORGANIZATION_FAILURE: null,

    CLEAR_COMMUNITY_LIST_ERROR: null,
    CLEAR_COMMUNITY_LIST: null,
    CLEAR_COMMUNITY_LIST_FILTER: null,
    CHANGE_COMMUNITY_LIST_FILTER: null,
    CHANGE_COMMUNITY_LIST_SORTING: null,
    LOAD_COMMUNITY_LIST_REQUEST: null,
    LOAD_COMMUNITY_LIST_SUCCESS: null,
    LOAD_COMMUNITY_LIST_FAILURE: null,

    CLEAR_COMMUNITY_HISTORY_ERROR: null,

    CLEAR_COMMUNITY_HISTORY: null,

    LOAD_COMMUNITY_HISTORY_REQUEST: null,
    LOAD_COMMUNITY_HISTORY_SUCCESS: null,
    LOAD_COMMUNITY_HISTORY_FAILURE: null,

    CLEAR_COMMUNITY_COUNT: null,
    CLEAR_COMMUNITY_COUNT_ERROR: null,
    LOAD_COMMUNITY_COUNT_REQUEST: null,
    LOAD_COMMUNITY_COUNT_SUCCESS: null,
    LOAD_COMMUNITY_COUNT_FAILURE: null,

    CLEAR_CAN_ADD_COMMUNITY: null,
    CLEAR_CAN_ADD_COMMUNITY_ERROR: null,
    LOAD_CAN_ADD_COMMUNITY_REQUEST: null,
    LOAD_CAN_ADD_COMMUNITY_SUCCESS: null,
    LOAD_CAN_ADD_COMMUNITY_FAILURE: null,

    CLEAR_COMMUNITY_DETAILS: null,
    CLEAR_COMMUNITY_DETAILS_ERROR: null,
    LOAD_COMMUNITY_DETAILS_REQUEST: null,
    LOAD_COMMUNITY_DETAILS_SUCCESS: null,
    LOAD_COMMUNITY_DETAILS_FAILURE: null,

    DOWNLOAD_COMMUNITY_LOGO_REQUEST: null,
    DOWNLOAD_COMMUNITY_LOGO_SUCCESS: null,
    DOWNLOAD_COMMUNITY_LOGO_FAILURE: null,

    CLEAR_COMMUNITY_FORM: null,
    CLEAR_COMMUNITY_FORM_ERROR: null,
    CLEAR_COMMUNITY_FORM_FIELD_ERROR: null,

    CHANGE_COMMUNITY_FORM_TAB: null,

    CHANGE_COMMUNITY_FORM_FIELD: null,
    CHANGE_COMMUNITY_FORM_FIELDS: null,
    CHANGE_COMMUNITY_FORM_MARKET_PLACE_FIELD: null,

    VALIDATE_COMMUNITY_FORM: null,
    VALIDATE_COMMUNITY_FORM_LEGAL_INFO: null,
    VALIDATE_COMMUNITY_FORM_MARKETPLACE: null,
    VALIDATE_COMMUNITY_FORM_AFFILIATE_RELATIONSHIP: null,

    VALIDATE_COMMUNITY_DATA_UNIQ_REQUEST: null,
    VALIDATE_COMMUNITY_DATA_UNIQ_SUCCESS: null,
    VALIDATE_COMMUNITY_DATA_UNIQ_FAILURE: null,

    SAVE_COMMUNITY_REQUEST: null,
    SAVE_COMMUNITY_SUCCESS: null,
    SAVE_COMMUNITY_FAILURE: null,

    CLEAR_COMMUNITY_HANDSET_LIST_ERROR: null,

    CLEAR_COMMUNITY_HANDSET_LIST: null,
    CLEAR_COMMUNITY_HANDSET_LIST_FILTER: null,
    CHANGE_COMMUNITY_HANDSET_LIST_FILTER: null,
    LOAD_COMMUNITY_HANDSET_LIST_REQUEST: null,
    LOAD_COMMUNITY_HANDSET_LIST_SUCCESS: null,
    LOAD_COMMUNITY_HANDSET_LIST_FAILURE: null,

    CLEAR_COMMUNITY_HANDSET_HISTORY_ERROR: null,

    CLEAR_COMMUNITY_HANDSET_HISTORY: null,
    LOAD_COMMUNITY_HANDSET_HISTORY_REQUEST: null,
    LOAD_COMMUNITY_HANDSET_HISTORY_SUCCESS: null,
    LOAD_COMMUNITY_HANDSET_HISTORY_FAILURE: null,

    CLEAR_COMMUNITY_HANDSET_COUNT: null,
    CLEAR_COMMUNITY_HANDSET_COUNT_ERROR: null,
    LOAD_COMMUNITY_HANDSET_COUNT_REQUEST: null,
    LOAD_COMMUNITY_HANDSET_COUNT_SUCCESS: null,
    LOAD_COMMUNITY_HANDSET_COUNT_FAILURE: null,

    CLEAR_COMMUNITY_HANDSET_FORM: null,
    CLEAR_COMMUNITY_HANDSET_FORM_ERROR: null,
    CLEAR_COMMUNITY_HANDSET_FORM_FIELD_ERROR: null,

    CHANGE_COMMUNITY_HANDSET_FORM_TAB: null,

    CHANGE_COMMUNITY_HANDSET_FORM_FIELD: null,
    CHANGE_COMMUNITY_HANDSET_FORM_FIELDS: null,

    VALIDATE_COMMUNITY_HANDSET_FORM: null,
    SAVE_COMMUNITY_HANDSET_REQUEST: null,
    SAVE_COMMUNITY_HANDSET_SUCCESS: null,
    SAVE_COMMUNITY_HANDSET_FAILURE: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_LIST_ERROR: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_LIST: null,
    CLEAR_COMMUNITY_DEVICE_TYPE_LIST_FILTER: null,
    CHANGE_COMMUNITY_DEVICE_TYPE_LIST_FILTER: null,
    LOAD_COMMUNITY_DEVICE_TYPE_LIST_REQUEST: null,
    LOAD_COMMUNITY_DEVICE_TYPE_LIST_SUCCESS: null,
    LOAD_COMMUNITY_DEVICE_TYPE_LIST_FAILURE: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_HISTORY_ERROR: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_HISTORY: null,
    LOAD_COMMUNITY_DEVICE_TYPE_HISTORY_REQUEST: null,
    LOAD_COMMUNITY_DEVICE_TYPE_HISTORY_SUCCESS: null,
    LOAD_COMMUNITY_DEVICE_TYPE_HISTORY_FAILURE: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_DETAILS: null,
    CLEAR_COMMUNITY_DEVICE_TYPE_DETAILS_ERROR: null,
    LOAD_COMMUNITY_DEVICE_TYPE_DETAILS_REQUEST: null,
    LOAD_COMMUNITY_DEVICE_TYPE_DETAILS_SUCCESS: null,
    LOAD_COMMUNITY_DEVICE_TYPE_DETAILS_FAILURE: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_COUNT: null,
    CLEAR_COMMUNITY_DEVICE_TYPE_COUNT_ERROR: null,
    LOAD_COMMUNITY_DEVICE_TYPE_COUNT_REQUEST: null,
    LOAD_COMMUNITY_DEVICE_TYPE_COUNT_SUCCESS: null,
    LOAD_COMMUNITY_DEVICE_TYPE_COUNT_FAILURE: null,

    CLEAR_COMMUNITY_DEVICE_TYPE_FORM: null,
    CLEAR_COMMUNITY_DEVICE_TYPE_FORM_ERROR: null,
    CLEAR_COMMUNITY_DEVICE_TYPE_FORM_FIELD_ERROR: null,

    CHANGE_COMMUNITY_DEVICE_TYPE_FORM_TAB: null,

    CHANGE_COMMUNITY_DEVICE_TYPE_FORM_FIELD: null,
    CHANGE_COMMUNITY_DEVICE_TYPE_FORM_FIELDS: null,

    VALIDATE_COMMUNITY_DEVICE_TYPE_FORM: null,
    SAVE_COMMUNITY_DEVICE_TYPE_REQUEST: null,
    SAVE_COMMUNITY_DEVICE_TYPE_SUCCESS: null,
    SAVE_COMMUNITY_DEVICE_TYPE_FAILURE: null,

    CLEAR_COMMUNITY_LOCATION_LIST_ERROR: null,

    CLEAR_COMMUNITY_LOCATION_LIST: null,
    CLEAR_COMMUNITY_LOCATION_LIST_FILTER: null,
    CHANGE_COMMUNITY_LOCATION_LIST_FILTER: null,
    LOAD_COMMUNITY_LOCATION_LIST_REQUEST: null,
    LOAD_COMMUNITY_LOCATION_LIST_SUCCESS: null,
    LOAD_COMMUNITY_LOCATION_LIST_FAILURE: null,

    CLEAR_COMMUNITY_LOCATION_HISTORY_ERROR: null,

    CLEAR_COMMUNITY_LOCATION_HISTORY: null,
    LOAD_COMMUNITY_LOCATION_HISTORY_REQUEST: null,
    LOAD_COMMUNITY_LOCATION_HISTORY_SUCCESS: null,
    LOAD_COMMUNITY_LOCATION_HISTORY_FAILURE: null,

    CLEAR_COMMUNITY_LOCATION_COUNT: null,
    CLEAR_COMMUNITY_LOCATION_COUNT_ERROR: null,
    LOAD_COMMUNITY_LOCATION_COUNT_REQUEST: null,
    LOAD_COMMUNITY_LOCATION_COUNT_SUCCESS: null,
    LOAD_COMMUNITY_LOCATION_COUNT_FAILURE: null,

    CLEAR_COMMUNITY_LOCATION_FORM: null,
    CLEAR_COMMUNITY_LOCATION_FORM_ERROR: null,
    CLEAR_COMMUNITY_LOCATION_FORM_FIELD_ERROR: null,

    CHANGE_COMMUNITY_LOCATION_FORM_TAB: null,

    CHANGE_COMMUNITY_LOCATION_FORM_FIELD: null,
    CHANGE_COMMUNITY_LOCATION_FORM_FIELDS: null,

    VALIDATE_COMMUNITY_LOCATION_FORM: null,
    SAVE_COMMUNITY_LOCATION_REQUEST: null,
    SAVE_COMMUNITY_LOCATION_SUCCESS: null,
    SAVE_COMMUNITY_LOCATION_FAILURE: null,

    CLEAR_COMMUNITY_ZONE_LIST_ERROR: null,

    CLEAR_COMMUNITY_ZONE_LIST: null,
    CLEAR_COMMUNITY_ZONE_LIST_FILTER: null,
    CHANGE_COMMUNITY_ZONE_LIST_FILTER: null,

    LOAD_COMMUNITY_ZONE_LIST_REQUEST: null,
    LOAD_COMMUNITY_ZONE_LIST_SUCCESS: null,
    LOAD_COMMUNITY_ZONE_LIST_FAILURE: null,

    CLEAR_COMMUNITY_ZONE_HISTORY_ERROR: null,

    CLEAR_COMMUNITY_ZONE_HISTORY: null,

    LOAD_COMMUNITY_ZONE_HISTORY_REQUEST: null,
    LOAD_COMMUNITY_ZONE_HISTORY_SUCCESS: null,
    LOAD_COMMUNITY_ZONE_HISTORY_FAILURE: null,

    CLEAR_COMMUNITY_ZONE_COUNT: null,
    CLEAR_COMMUNITY_ZONE_COUNT_ERROR: null,
    LOAD_COMMUNITY_ZONE_COUNT_REQUEST: null,
    LOAD_COMMUNITY_ZONE_COUNT_SUCCESS: null,
    LOAD_COMMUNITY_ZONE_COUNT_FAILURE: null,

    CLEAR_COMMUNITY_ZONE_FORM: null,
    CLEAR_COMMUNITY_ZONE_FORM_ERROR: null,
    CLEAR_COMMUNITY_ZONE_FORM_FIELD_ERROR: null,

    CHANGE_COMMUNITY_ZONE_FORM_TAB: null,

    CHANGE_COMMUNITY_ZONE_FORM_FIELD: null,
    CHANGE_COMMUNITY_ZONE_FORM_FIELDS: null,

    VALIDATE_COMMUNITY_ZONE_FORM: null,
    SAVE_COMMUNITY_ZONE_REQUEST: null,
    SAVE_COMMUNITY_ZONE_SUCCESS: null,
    SAVE_COMMUNITY_ZONE_FAILURE: null,

    UPDATE_SIDE_BAR: null,

    CLEAR_STATE_LIST: null,
    LOAD_STATE_LIST_SUCCESS: null,
    LOAD_STATE_LIST_FAILURE: null,

    CLEAR_GENDER_LIST: null,
    LOAD_GENDER_LIST_SUCCESS: null,
    LOAD_GENDER_LIST_FAILURE: null,

    CLEAR_MARITAL_STATUS_LIST: null,
    LOAD_MARITAL_STATUS_LIST_SUCCESS: null,
    LOAD_MARITAL_STATUS_LIST_FAILURE: null,

    CLEAR_AGE_GROUP_LIST: null,
    LOAD_AGE_GROUP_LIST_SUCCESS: null,
    LOAD_AGE_GROUP_LIST_FAILURE: null,

    CLEAR_PRIMARY_FOCUS_LIST: null,
    LOAD_PRIMARY_FOCUS_LIST_REQUEST: null,
    LOAD_PRIMARY_FOCUS_LIST_SUCCESS: null,
    LOAD_PRIMARY_FOCUS_LIST_FAILURE: null,

    CLEAR_CARE_LEVEL_LIST: null,
    LOAD_CARE_LEVEL_LIST_SUCCESS: null,
    LOAD_CARE_LEVEL_LIST_FAILURE: null,

    CLEAR_NOTE_TYPE_LIST: null,
    LOAD_NOTE_TYPE_LIST_SUCCESS: null,
    LOAD_NOTE_TYPE_LIST_FAILURE: null,

    CLEAR_NOTE_ENCOUNTER_TYPE_LIST: null,
    LOAD_NOTE_ENCOUNTER_TYPE_LIST_SUCCESS: null,
    LOAD_NOTE_ENCOUNTER_TYPE_LIST_FAILURE: null,

    CLEAR_NOTE_ADMITTANCE_LIST: null,
    LOAD_NOTE_ADMITTANCE_LIST_SUCCESS: null,
    LOAD_NOTE_ADMITTANCE_LIST_FAILURE: null,

    CLEAR_EVENT_TYPE_LIST: null,
    LOAD_EVENT_TYPE_LIST_SUCCESS: null,
    LOAD_EVENT_TYPE_LIST_FAILURE: null,

    CLEAR_COMMUNITY_TYPE_LIST: null,
    LOAD_COMMUNITY_TYPE_LIST_REQUEST: null,
    LOAD_COMMUNITY_TYPE_LIST_SUCCESS: null,
    LOAD_COMMUNITY_TYPE_LIST_FAILURE: null,

    CLEAR_LANGUAGE_SERVICE_LIST: null,
    LOAD_LANGUAGE_SERVICE_LIST_SUCCESS: null,
    LOAD_LANGUAGE_SERVICE_LIST_FAILURE: null,

    CLEAR_ADDITIONAL_SERVICE_LIST: null,
    LOAD_ADDITIONAL_SERVICE_LIST_SUCCESS: null,
    LOAD_ADDITIONAL_SERVICE_LIST_FAILURE: null,

    CLEAR_TREATMENT_SERVICE_LIST: null,
    LOAD_TREATMENT_SERVICE_LIST_REQUEST: null,
    LOAD_TREATMENT_SERVICE_LIST_SUCCESS: null,
    LOAD_TREATMENT_SERVICE_LIST_FAILURE: null,

    CLEAR_EMERGENCY_SERVICE_LIST: null,
    LOAD_EMERGENCY_SERVICE_LIST_SUCCESS: null,
    LOAD_EMERGENCY_SERVICE_LIST_FAILURE: null,

    CLEAR_DOMAIN_LIST: null,
    LOAD_DOMAIN_LIST_SUCCESS: null,
    LOAD_DOMAIN_LIST_FAILURE: null,

    CLEAR_PRIORITY_LIST: null,
    LOAD_PRIORITY_LIST_SUCCESS: null,
    LOAD_PRIORITY_LIST_FAILURE: null,

    CLEAR_ORGANIZATION_TYPE_LIST: null,
    LOAD_ORGANIZATION_TYPE_LIST_SUCCESS: null,
    LOAD_ORGANIZATION_TYPE_LIST_FAILURE: null,

    CLEAR_SYSTEM_ROLE_LIST: null,
    LOAD_SYSTEM_ROLE_LIST_SUCCESS: null,
    LOAD_SYSTEM_ROLE_LIST_FAILURE: null,

    CLEAR_CARE_TEAM_EMPLOYEE_LIST: null,
    LOAD_CARE_TEAM_EMPLOYEE_LIST_SUCCESS: null,
    LOAD_CARE_TEAM_EMPLOYEE_LIST_FAILURE: null,

    CLEAR_CARE_TEAM_ROLE_LIST: null,
    LOAD_CARE_TEAM_ROLE_LIST_SUCCESS: null,
    LOAD_CARE_TEAM_ROLE_LIST_FAILURE: null,

    CLEAR_CARE_TEAM_CHANNEL_LIST: null,
    LOAD_CARE_TEAM_CHANNEL_LIST_SUCCESS: null,
    LOAD_CARE_TEAM_CHANNEL_LIST_FAILURE: null,

    CLEAR_CARE_TEAM_RESPONSIBILITY_LIST: null,
    LOAD_CARE_TEAM_RESPONSIBILITY_LIST_SUCCESS: null,
    LOAD_CARE_TEAM_RESPONSIBILITY_LIST_FAILURE: null,

    CLEAR_CARE_TEAM_NOTIFICATION_PREFERENCE_LIST: null,
    LOAD_CARE_TEAM_NOTIFICATION_PREFERENCE_LIST_SUCCESS: null,
    LOAD_CARE_TEAM_NOTIFICATION_PREFERENCE_LIST_FAILURE: null,

    CLEAR_DIRECTORY_ORGANIZATION_LIST: null,
    LOAD_DIRECTORY_ORGANIZATION_LIST_SUCCESS: null,
    LOAD_DIRECTORY_ORGANIZATION_LIST_FAILURE: null,

    CLEAR_DIRECTORY_COMMUNITY_LIST: null,
    LOAD_DIRECTORY_COMMUNITY_LIST_SUCCESS: null,
    LOAD_DIRECTORY_COMMUNITY_LIST_FAILURE: null,

    CLEAR_CLIENT_COMMUNITY_LIST: null,
    LOAD_CLIENT_COMMUNITY_LIST_SUCCESS: null,
    LOAD_CLIENT_COMMUNITY_LIST_FAILURE: null,

    CLEAR_CONTACT_COMMUNITY_LIST: null,
    LOAD_CONTACT_COMMUNITY_LIST_REQUEST: null,
    LOAD_CONTACT_COMMUNITY_LIST_SUCCESS: null,
    LOAD_CONTACT_COMMUNITY_LIST_FAILURE: null,

    CLEAR_EVENT_COMMUNITY_LIST: null,
    LOAD_EVENT_COMMUNITY_LIST_SUCCESS: null,
    LOAD_EVENT_COMMUNITY_LIST_FAILURE: null,

    CLEAR_CONTACT_STATUS_LIST: null,
    LOAD_CONTACT_STATUS_LIST_REQUEST: null,
    LOAD_CONTACT_STATUS_LIST_SUCCESS: null,
    LOAD_CONTACT_STATUS_LIST_FAILURE: null,

    CLEAR_CONTACT_LIST_ERROR: null,

    CLEAR_CONTACT_LIST: null,

    CLEAR_CONTACT_LIST_FILTER: null,
    CHANGE_CONTACT_LIST_FILTER: null,
    CHANGE_CONTACT_LIST_FILTER_FIELD: null,
    LOAD_CONTACT_LIST_REQUEST: null,
    LOAD_CONTACT_LIST_SUCCESS: null,
    LOAD_CONTACT_LIST_FAILURE: null,
    CHANGE_CONTACT_LIST_SORTING: null,

    DOWNLOAD_CONTACT_AVATAR_REQUEST: null,
    DOWNLOAD_CONTACT_AVATAR_SUCCESS: null,
    DOWNLOAD_CONTACT_AVATAR_FAILURE: null,

    CLEAR_CONTACT_HISTORY_ERROR: null,

    CLEAR_CONTACT_HISTORY: null,

    LOAD_CONTACT_HISTORY_REQUEST: null,
    LOAD_CONTACT_HISTORY_SUCCESS: null,
    LOAD_CONTACT_HISTORY_FAILURE: null,

    CLEAR_CONTACT_COUNT: null,
    CLEAR_CONTACT_COUNT_ERROR: null,
    LOAD_CONTACT_COUNT_REQUEST: null,
    LOAD_CONTACT_COUNT_SUCCESS: null,
    LOAD_CONTACT_COUNT_FAILURE: null,

    CLEAR_CAN_ADD_CONTACT: null,
    CLEAR_CAN_ADD_CONTACT_ERROR: null,
    LOAD_CAN_ADD_CONTACT_REQUEST: null,
    LOAD_CAN_ADD_CONTACT_SUCCESS: null,
    LOAD_CAN_ADD_CONTACT_FAILURE: null,

    CLEAR_CONTACT_DETAILS: null,
    CLEAR_CONTACT_DETAILS_ERROR: null,
    LOAD_CONTACT_DETAILS_REQUEST: null,
    LOAD_CONTACT_DETAILS_SUCCESS: null,
    LOAD_CONTACT_DETAILS_FAILURE: null,

    CLEAR_CONTACT_FORM: null,
    CLEAR_CONTACT_FORM_ERROR: null,
    CLEAR_CONTACT_FORM_FIELD_ERROR: null,

    CHANGE_CONTACT_FORM_TAB: null,

    CHANGE_CONTACT_FORM_FIELD: null,
    CHANGE_CONTACT_FORM_FIELDS: null,

    VALIDATE_CONTACT_FORM: null,

    VALIDATE_CONTACT_DATA_UNIQ_REQUEST: null,
    VALIDATE_CONTACT_DATA_UNIQ_SUCCESS: null,
    VALIDATE_CONTACT_DATA_UNIQ_FAILURE: null,

    SAVE_CONTACT_REQUEST: null,
    SAVE_CONTACT_SUCCESS: null,
    SAVE_CONTACT_FAILURE: null,

    INVITE_CONTACT_REQUEST: null,
    INVITE_CONTACT_SUCCESS: null,
    INVITE_CONTACT_FAILURE: null,

    CLEAR_CLIENT_LIST_ERROR: null,
    CLEAR_CLIENT_LIST: null,
    CLEAR_CLIENT_LIST_FILTER: null,
    CHANGE_CLIENT_LIST_FILTER: null,
    CHANGE_CLIENT_LIST_FILTER_FIELD: null,
    LOAD_CLIENT_LIST_REQUEST: null,
    LOAD_CLIENT_LIST_SUCCESS: null,
    LOAD_CLIENT_LIST_FAILURE: null,
    CHANGE_CLIENT_LIST_SORTING: null,

    CLEAR_CLIENT_HISTORY_ERROR: null,
    CLEAR_CLIENT_HISTORY: null,
    LOAD_CLIENT_HISTORY_REQUEST: null,
    LOAD_CLIENT_HISTORY_SUCCESS: null,
    LOAD_CLIENT_HISTORY_FAILURE: null,

    CLEAR_CLIENT_COUNT: null,
    CLEAR_CLIENT_COUNT_ERROR: null,
    LOAD_CLIENT_COUNT_REQUEST: null,
    LOAD_CLIENT_COUNT_SUCCESS: null,
    LOAD_CLIENT_COUNT_FAILURE: null,

    CLEAR_CLIENT_DETAILS: null,
    CLEAR_CLIENT_DETAILS_ERROR: null,
    LOAD_CLIENT_DETAILS_REQUEST: null,
    LOAD_CLIENT_DETAILS_SUCCESS: null,
    LOAD_CLIENT_DETAILS_FAILURE: null,

    CLEAR_CLIENT_BILLING_DETAILS: null,
    CLEAR_CLIENT_BILLING_DETAILS_ERROR: null,

    LOAD_CLIENT_BILLING_DETAILS_REQUEST: null,
    LOAD_CLIENT_BILLING_DETAILS_SUCCESS: null,
    LOAD_CLIENT_BILLING_DETAILS_FAILURE: null,

    CLEAR_CLIENT_EMERGENCY_CONTACT_LIST_ERROR: null,
    CLEAR_CLIENT_EMERGENCY_CONTACT_LIST: null,
    LOAD_CLIENT_EMERGENCY_CONTACT_LIST_REQUEST: null,
    LOAD_CLIENT_EMERGENCY_CONTACT_LIST_SUCCESS: null,
    LOAD_CLIENT_EMERGENCY_CONTACT_LIST_FAILURE: null,

    DOWNLOAD_CLIENT_EMERGENCY_CONTACT_AVATAR_REQUEST: null,
    DOWNLOAD_CLIENT_EMERGENCY_CONTACT_AVATAR_SUCCESS: null,
    DOWNLOAD_CLIENT_EMERGENCY_CONTACT_AVATAR_FAILURE: null,

    CLEAR_CLIENT_FORM: null,
    CLEAR_CLIENT_FORM_ERROR: null,
    CLEAR_CLIENT_FORM_FIELD_ERROR: null,

    CHANGE_CLIENT_FORM_TAB: null,

    CHANGE_CLIENT_FORM_FIELD: null,
    CHANGE_CLIENT_FORM_ADDRESS_FIELD: null,

    CHANGE_CLIENT_FORM_FIELDS: null,

    SAVE_CLIENT_REQUEST: null,
    SAVE_CLIENT_SUCCESS: null,
    SAVE_CLIENT_FAILURE: null,

    CLEAR_CLIENT_STATUS_LIST: null,
    LOAD_CLIENT_STATUS_LIST_REQUEST: null,
    LOAD_CLIENT_STATUS_LIST_SUCCESS: null,
    LOAD_CLIENT_STATUS_LIST_FAILURE: null,

    VALIDATE_CLIENT_FORM: null,

    VALIDATE_CLIENT_DATA_UNIQ_REQUEST: null,
    VALIDATE_CLIENT_DATA_UNIQ_SUCCESS: null,
    VALIDATE_CLIENT_DATA_UNIQ_FAILURE: null,

    VALIDATE_CLIENT_DATA_UNIQ_IN_COMMUNITY_REQUEST: null,
    VALIDATE_CLIENT_DATA_UNIQ_IN_COMMUNITY_SUCCESS: null,
    VALIDATE_CLIENT_DATA_UNIQ_IN_COMMUNITY_FAILURE: null,

    VALIDATE_CLIENT_DATA_UNIQ_IN_ORGANIZATION_REQUEST: null,
    VALIDATE_CLIENT_DATA_UNIQ_IN_ORGANIZATION_SUCCESS: null,
    VALIDATE_CLIENT_DATA_UNIQ_IN_ORGANIZATION_FAILURE: null,

    CLEAR_CASELOAD_HISTORY_ERROR: null,
    CLEAR_CASELOAD_HISTORY: null,
    LOAD_CASELOAD_HISTORY_REQUEST: null,
    LOAD_CASELOAD_HISTORY_SUCCESS: null,
    LOAD_CASELOAD_HISTORY_FAILURE: null,

    CLEAR_CASELOAD_FORM: null,
    CLEAR_CASELOAD_FORM_ERROR: null,
    CLEAR_CASELOAD_FORM_FIELD_ERROR: null,

    CHANGE_CASELOAD_FORM_TAB: null,

    ADD_CASELOAD_FORM: null,
    REMOVE_CASELOAD_FORM: null,
    CHANGE_CASELOAD_FORM_FIELD: null,
    CHANGE_CASELOAD_FORM_FIELDS: null,
    UPDATE_CASELOAD_FORM_CLIENT_LIST: null,

    CLEAR_CASELOAD_FORM_FILTER: null,
    CHANGE_CASELOAD_FORM_FILTER: null,

    VALIDATE_CASELOAD_FORM: null,

    SAVE_CASELOAD_REQUEST: null,
    SAVE_CASELOAD_SUCCESS: null,
    SAVE_CASELOAD_FAILURE: null,

    CLEAR_ASSESSMENT_LIST_ERROR: null,
    CLEAR_ASSESSMENT_LIST: null,
    CLEAR_ASSESSMENT_LIST_FILTER: null,
    CHANGE_ASSESSMENT_LIST_FILTER: null,
    LOAD_ASSESSMENT_LIST_REQUEST: null,
    LOAD_ASSESSMENT_LIST_SUCCESS: null,
    LOAD_ASSESSMENT_LIST_FAILURE: null,
    CHANGE_ASSESSMENT_LIST_SORTING: null,

    CLEAR_ASSESSMENT_COUNT: null,
    CLEAR_ASSESSMENT_COUNT_ERROR: null,
    LOAD_ASSESSMENT_COUNT_REQUEST: null,
    LOAD_ASSESSMENT_COUNT_SUCCESS: null,
    LOAD_ASSESSMENT_COUNT_FAILURE: null,

    CLEAR_ASSESSMENT_DETAILS: null,
    CLEAR_ASSESSMENT_DETAILS_ERROR: null,
    LOAD_ASSESSMENT_DETAILS_REQUEST: null,
    LOAD_ASSESSMENT_DETAILS_SUCCESS: null,
    LOAD_ASSESSMENT_DETAILS_FAILURE: null,

    CLEAR_ASSESSMENT_SURVEY: null,
    CLEAR_ASSESSMENT_SURVEY_ERROR: null,
    LOAD_ASSESSMENT_SURVEY_REQUEST: null,
    LOAD_ASSESSMENT_SURVEY_SUCCESS: null,
    LOAD_ASSESSMENT_SURVEY_FAILURE: null,

    CLEAR_ASSESSMENT_FORM: null,
    CLEAR_ASSESSMENT_FORM_ERROR: null,
    CLEAR_ASSESSMENT_FORM_FIELD_ERROR: null,

    CHANGE_ASSESSMENT_FORM_TAB: null,

    CHANGE_ASSESSMENT_FORM_FIELD: null,
    CHANGE_ASSESSMENT_FORM_FIELDS: null,

    VALIDATE_ASSESSMENT_FORM: null,

    SAVE_ASSESSMENT_REQUEST: null,
    SAVE_ASSESSMENT_SUCCESS: null,
    SAVE_ASSESSMENT_FAILURE: null,

    CLEAR_ASSESSMENT_HISTORY_ERROR: null,

    CLEAR_ASSESSMENT_HISTORY: null,

    LOAD_ASSESSMENT_HISTORY_REQUEST: null,
    LOAD_ASSESSMENT_HISTORY_SUCCESS: null,
    LOAD_ASSESSMENT_HISTORY_FAILURE: null,

    CLEAR_ASSESSMENT_SCORE: null,
    CLEAR_ASSESSMENT_SCORE_ERROR: null,
    LOAD_ASSESSMENT_SCORE_REQUEST: null,
    LOAD_ASSESSMENT_SCORE_SUCCESS: null,
    LOAD_ASSESSMENT_SCORE_FAILURE: null,

    CLEAR_ASSESSMENT_MANAGEMENT: null,
    CLEAR_ASSESSMENT_MANAGEMENT_ERROR: null,
    LOAD_ASSESSMENT_MANAGEMENT_REQUEST: null,
    LOAD_ASSESSMENT_MANAGEMENT_SUCCESS: null,
    LOAD_ASSESSMENT_MANAGEMENT_FAILURE: null,

    CLEAR_ASSESSMENT_DIAGNOSTIC_SCALE: null,
    CLEAR_ASSESSMENT_DIAGNOSTIC_SCALE_ERROR: null,
    LOAD_ASSESSMENT_DIAGNOSTIC_SCALE_REQUEST: null,
    LOAD_ASSESSMENT_DIAGNOSTIC_SCALE_SUCCESS: null,
    LOAD_ASSESSMENT_DIAGNOSTIC_SCALE_FAILURE: null,

    CLEAR_ASSESSMENT_TYPE_LIST: null,
    CLEAR_ASSESSMENT_TYPE_LIST_ERROR: null,
    LOAD_ASSESSMENT_TYPE_LIST_REQUEST: null,
    LOAD_ASSESSMENT_TYPE_LIST_SUCCESS: null,
    LOAD_ASSESSMENT_TYPE_LIST_FAILURE: null,

    CLEAR_SERVICE_PLAN_LIST_ERROR: null,
    CLEAR_SERVICE_PLAN_LIST: null,
    CLEAR_SERVICE_PLAN_LIST_FILTER: null,
    CHANGE_SERVICE_PLAN_LIST_FILTER: null,
    LOAD_SERVICE_PLAN_LIST_REQUEST: null,
    LOAD_SERVICE_PLAN_LIST_SUCCESS: null,
    LOAD_SERVICE_PLAN_LIST_FAILURE: null,
    CHANGE_SERVICE_PLAN_LIST_SORTING: null,

    CLEAR_SERVICE_PLAN_HISTORY_ERROR: null,

    CLEAR_SERVICE_PLAN_HISTORY: null,

    LOAD_SERVICE_PLAN_HISTORY_REQUEST: null,
    LOAD_SERVICE_PLAN_HISTORY_SUCCESS: null,
    LOAD_SERVICE_PLAN_HISTORY_FAILURE: null,

    CLEAR_SERVICE_PLAN_COUNT: null,
    CLEAR_SERVICE_PLAN_COUNT_ERROR: null,
    LOAD_SERVICE_PLAN_COUNT_REQUEST: null,
    LOAD_SERVICE_PLAN_COUNT_SUCCESS: null,
    LOAD_SERVICE_PLAN_COUNT_FAILURE: null,

    CLEAR_SERVICE_PLAN_DETAILS: null,
    CLEAR_SERVICE_PLAN_DETAILS_ERROR: null,
    LOAD_SERVICE_PLAN_DETAILS_REQUEST: null,
    LOAD_SERVICE_PLAN_DETAILS_SUCCESS: null,
    LOAD_SERVICE_PLAN_DETAILS_FAILURE: null,

    DOWNLOAD_SERVICE_PLAN_DETAILS_REQUEST: null,
    DOWNLOAD_SERVICE_PLAN_DETAILS_SUCCESS: null,
    DOWNLOAD_SERVICE_PLAN_DETAILS_FAILURE: null,

    CLEAR_SERVICE_PLAN_FORM: null,
    CLEAR_SERVICE_PLAN_FORM_ERROR: null,
    CLEAR_SERVICE_PLAN_FORM_FIELD_ERROR: null,

    CHANGE_SERVICE_PLAN_FORM_TAB: null,

    CHANGE_SERVICE_PLAN_FORM_FIELD: null,
    CHANGE_SERVICE_PLAN_FORM_FIELDS: null,

    VALIDATE_SERVICE_PLAN_FORM: null,
    VALIDATE_SERVICE_PLAN_NEED_SECTION: null,
    VALIDATE_SERVICE_PLAN_GOAL_SECTION: null,

    SAVE_SERVICE_PLAN_REQUEST: null,
    SAVE_SERVICE_PLAN_SUCCESS: null,
    SAVE_SERVICE_PLAN_FAILURE: null,

    ADD_SERVICE_PLAN_ANCHOR: null,
    REMOVE_SERVICE_PLAN_ANCHOR: null,
    CHANGE_SERVICE_PLAN_ANCHORS: null,

    ADD_SERVICE_PLAN_FORM_NEED: null,
    REMOVE_SERVICE_PLAN_FORM_NEED: null,
    CHANGE_SERVICE_PLAN_FORM_NEED_FIELD: null,
    CHANGE_SERVICE_PLAN_FORM_NEED_FIELDS: null,
    CLEAR_SERVICE_PLAN_FORM_NEED_FIELDS: null,
    CHANGE_SERVICE_PLAN_FORM_NEED_SCORE_FIELD: null,

    ADD_SERVICE_PLAN_FORM_GOAL: null,
    REMOVE_SERVICE_PLAN_FORM_GOAL: null,
    CHANGE_SERVICE_PLAN_FORM_GOAL_FIELD: null,
    CHANGE_SERVICE_PLAN_FORM_GOAL_FIELDS: null,

    CLEAR_CARE_CLIENT_LIST_ERROR: null,
    CLEAR_CARE_CLIENT_LIST: null,
    CLEAR_CARE_CLIENT_LIST_FILTER: null,
    CHANGE_CARE_CLIENT_LIST_FILTER: null,
    LOAD_CARE_CLIENT_LIST_REQUEST: null,
    LOAD_CARE_CLIENT_LIST_SUCCESS: null,
    LOAD_CARE_CLIENT_LIST_FAILURE: null,

    CLEAR_CARE_CLIENT_HISTORY_ERROR: null,
    CLEAR_CARE_CLIENT_HISTORY: null,
    LOAD_CARE_CLIENT_HISTORY_REQUEST: null,
    LOAD_CARE_CLIENT_HISTORY_SUCCESS: null,
    LOAD_CARE_CLIENT_HISTORY_FAILURE: null,

    CLEAR_CARE_CLIENT_COUNT: null,
    CLEAR_CARE_CLIENT_COUNT_ERROR: null,
    LOAD_CARE_CLIENT_COUNT_REQUEST: null,
    LOAD_CARE_CLIENT_COUNT_SUCCESS: null,
    LOAD_CARE_CLIENT_COUNT_FAILURE: null,

    CLEAR_CARE_CLIENT_DETAILS: null,
    CLEAR_CARE_CLIENT_DETAILS_ERROR: null,
    LOAD_CARE_CLIENT_DETAILS_REQUEST: null,
    LOAD_CARE_CLIENT_DETAILS_SUCCESS: null,
    LOAD_CARE_CLIENT_DETAILS_FAILURE: null,

    CLEAR_CARE_CLIENT_FORM: null,
    CLEAR_CARE_CLIENT_FORM_ERROR: null,
    CLEAR_CARE_CLIENT_FORM_FIELD_ERROR: null,

    CHANGE_CARE_CLIENT_FORM_TAB: null,

    CHANGE_CARE_CLIENT_FORM_FIELD: null,
    CHANGE_CARE_CLIENT_FORM_FIELDS: null,

    VALIDATE_CARE_CLIENT_FORM: null,

    SAVE_CARE_CLIENT_REQUEST: null,
    SAVE_CARE_CLIENT_SUCCESS: null,
    SAVE_CARE_CLIENT_FAILURE: null,

    DOWNLOAD_CLIENT_AVATAR_REQUEST: null,
    DOWNLOAD_CLIENT_AVATAR_SUCCESS: null,
    DOWNLOAD_CLIENT_AVATAR_FAILURE: null,

    CLEAR_CARE_TEAM_MEMBER_LIST_ERROR: null,
    CLEAR_CARE_TEAM_MEMBER_LIST: null,
    CLEAR_CARE_TEAM_MEMBER_LIST_FILTER: null,
    CHANGE_CARE_TEAM_MEMBER_LIST_FILTER: null,
    LOAD_CARE_TEAM_MEMBER_LIST_REQUEST: null,
    LOAD_CARE_TEAM_MEMBER_LIST_SUCCESS: null,
    LOAD_CARE_TEAM_MEMBER_LIST_FAILURE: null,

    CLEAR_CARE_TEAM_MEMBER_HISTORY_ERROR: null,
    CLEAR_CARE_TEAM_MEMBER_HISTORY: null,
    LOAD_CARE_TEAM_MEMBER_HISTORY_REQUEST: null,
    LOAD_CARE_TEAM_MEMBER_HISTORY_SUCCESS: null,
    LOAD_CARE_TEAM_MEMBER_HISTORY_FAILURE: null,

    CLEAR_CARE_TEAM_MEMBER_COUNT: null,
    CLEAR_CARE_TEAM_MEMBER_COUNT_ERROR: null,
    LOAD_CARE_TEAM_MEMBER_COUNT_REQUEST: null,
    LOAD_CARE_TEAM_MEMBER_COUNT_SUCCESS: null,
    LOAD_CARE_TEAM_MEMBER_COUNT_FAILURE: null,

    CLEAR_CARE_TEAM_MEMBER_DETAILS: null,
    CLEAR_CARE_TEAM_MEMBER_DETAILS_ERROR: null,
    LOAD_CARE_TEAM_MEMBER_DETAILS_REQUEST: null,
    LOAD_CARE_TEAM_MEMBER_DETAILS_SUCCESS: null,
    LOAD_CARE_TEAM_MEMBER_DETAILS_FAILURE: null,

    CLEAR_CARE_TEAM_MEMBER_FORM: null,
    CLEAR_CARE_TEAM_MEMBER_FORM_ERROR: null,
    CLEAR_CARE_TEAM_MEMBER_FORM_FIELD_ERROR: null,

    CHANGE_CARE_TEAM_MEMBER_FORM_TAB: null,

    CHANGE_CARE_TEAM_MEMBER_FORM_FIELD: null,
    CHANGE_CARE_TEAM_MEMBER_FORM_FIELDS: null,

    VALIDATE_CARE_TEAM_MEMBER_FORM: null,

    SAVE_CARE_TEAM_MEMBER_REQUEST: null,
    SAVE_CARE_TEAM_MEMBER_SUCCESS: null,
    SAVE_CARE_TEAM_MEMBER_FAILURE: null,

    CLEAR_DASHBOARD_SERVICE_PLAN_COUNT: null,
    CLEAR_DASHBOARD_SERVICE_PLAN_COUNT_ERROR: null,
    LOAD_DASHBOARD_SERVICE_PLAN_COUNT_REQUEST: null,
    LOAD_DASHBOARD_SERVICE_PLAN_COUNT_SUCCESS: null,
    LOAD_DASHBOARD_SERVICE_PLAN_COUNT_FAILURE: null,

    CLEAR_DASHBOARD_ASSESSMENT_COUNT: null,
    CLEAR_DASHBOARD_ASSESSMENT_COUNT_ERROR: null,
    LOAD_DASHBOARD_ASSESSMENT_COUNT_REQUEST: null,
    LOAD_DASHBOARD_ASSESSMENT_COUNT_SUCCESS: null,
    LOAD_DASHBOARD_ASSESSMENT_COUNT_FAILURE: null,

    CLEAR_DASHBOARD_CASELOAD_LIST: null,
    CLEAR_DASHBOARD_CASELOAD_LIST_ERROR: null,
    CLEAR_DASHBOARD_CASELOAD_LIST_FILTER: null,
    CHANGE_DASHBOARD_CASELOAD_LIST_FILTER: null,
    LOAD_DASHBOARD_CASELOAD_LIST_REQUEST: null,
    LOAD_DASHBOARD_CASELOAD_LIST_SUCCESS: null,
    LOAD_DASHBOARD_CASELOAD_LIST_FAILURE: null,

    CLEAR_DASHBOARD_CASELOAD_HISTORY: null,

    CLEAR_DASHBOARD_CASELOAD_HISTORY_ERROR: null,

    LOAD_DASHBOARD_CASELOAD_HISTORY_REQUEST: null,
    LOAD_DASHBOARD_CASELOAD_HISTORY_SUCCESS: null,
    LOAD_DASHBOARD_CASELOAD_HISTORY_FAILURE: null,

    CLEAR_DASHBOARD_APPOINTMENT_LIST: null,
    CLEAR_DASHBOARD_APPOINTMENT_LIST_ERROR: null,
    CLEAR_DASHBOARD_APPOINTMENT_LIST_FILTER: null,
    CHANGE_DASHBOARD_APPOINTMENT_LIST_FILTER: null,
    LOAD_DASHBOARD_APPOINTMENT_LIST_REQUEST: null,
    LOAD_DASHBOARD_APPOINTMENT_LIST_SUCCESS: null,
    LOAD_DASHBOARD_APPOINTMENT_LIST_FAILURE: null,

    CLEAR_DASHBOARD_APPOINTMENT_HISTORY: null,
    CLEAR_DASHBOARD_APPOINTMENT_HISTORY_ERROR: null,
    LOAD_DASHBOARD_APPOINTMENT_HISTORY_REQUEST: null,
    LOAD_DASHBOARD_APPOINTMENT_HISTORY_SUCCESS: null,
    LOAD_DASHBOARD_APPOINTMENT_HISTORY_FAILURE: null,

    CLEAR_DASHBOARD_EVENT_LIST: null,
    CLEAR_DASHBOARD_EVENT_LIST_ERROR: null,
    CLEAR_DASHBOARD_EVENT_LIST_FILTER: null,
    CHANGE_DASHBOARD_EVENT_LIST_FILTER: null,
    LOAD_DASHBOARD_EVENT_LIST_REQUEST: null,
    LOAD_DASHBOARD_EVENT_LIST_SUCCESS: null,
    LOAD_DASHBOARD_EVENT_LIST_FAILURE: null,

    CLEAR_DASHBOARD_NOTE_LIST: null,
    CLEAR_DASHBOARD_NOTE_LIST_ERROR: null,
    CLEAR_DASHBOARD_NOTE_LIST_FILTER: null,
    CHANGE_DASHBOARD_NOTE_LIST_FILTER: null,
    LOAD_DASHBOARD_NOTE_LIST_REQUEST: null,
    LOAD_DASHBOARD_NOTE_LIST_SUCCESS: null,
    LOAD_DASHBOARD_NOTE_LIST_FAILURE: null,

    CLEAR_MARKETPLACE_COMMUNITY_LIST_ERROR: null,

    CLEAR_MARKETPLACE_COMMUNITY_LIST: null,

    CLEAR_MARKETPLACE_COMMUNITY_LIST_FILTER: null,
    CHANGE_MARKETPLACE_COMMUNITY_LIST_FILTER: null,
    CHANGE_MARKETPLACE_COMMUNITY_LIST_FILTER_FIELD: null,
    LOAD_MARKETPLACE_COMMUNITY_LIST_REQUEST: null,
    LOAD_MARKETPLACE_COMMUNITY_LIST_SUCCESS: null,
    LOAD_MARKETPLACE_COMMUNITY_LIST_FAILURE: null,

    CLEAR_MARKETPLACE_COMMUNITY_LOCATION_LIST: null,
    LOAD_MARKETPLACE_COMMUNITY_LOCATION_LIST_SUCCESS: null,
    LOAD_MARKETPLACE_COMMUNITY_LOCATION_LIST_FAILURE: null,

    CLEAR_MARKETPLACE_COMMUNITY_HISTORY_ERROR: null,

    CLEAR_MARKETPLACE_COMMUNITY_HISTORY: null,

    LOAD_MARKETPLACE_COMMUNITY_HISTORY_REQUEST: null,
    LOAD_MARKETPLACE_COMMUNITY_HISTORY_SUCCESS: null,
    LOAD_MARKETPLACE_COMMUNITY_HISTORY_FAILURE: null,

    CLEAR_MARKETPLACE_COMMUNITY_DETAILS: null,
    CLEAR_MARKETPLACE_COMMUNITY_DETAILS_ERROR: null,
    LOAD_MARKETPLACE_COMMUNITY_DETAILS_REQUEST: null,
    LOAD_MARKETPLACE_COMMUNITY_DETAILS_SUCCESS: null,
    LOAD_MARKETPLACE_COMMUNITY_DETAILS_FAILURE: null,

    CLEAR_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM: null,
    CLEAR_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM_ERROR: null,
    CLEAR_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM_FIELD_ERROR: null,

    CHANGE_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM_TAB: null,

    CHANGE_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM_FIELD: null,
    CHANGE_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM_FIELDS: null,

    VALIDATE_MARKETPLACE_COMMUNITY_APPOINTMENT_FORM: null,

    SAVE_MARKETPLACE_COMMUNITY_APPOINTMENT_REQUEST: null,
    SAVE_MARKETPLACE_COMMUNITY_APPOINTMENT_SUCCESS: null,
    SAVE_MARKETPLACE_COMMUNITY_APPOINTMENT_FAILURE: null,

    CLEAR_MARKETPLACE_COMMUNITY_FILTER: null,
    CHANGE_MARKETPLACE_COMMUNITY_FILTER_FIELD: null,

    CLEAR_EVENT_LIST_ERROR: null,

    CLEAR_EVENT_LIST: null,

    CLEAR_EVENT_LIST_FILTER: null,
    CHANGE_EVENT_LIST_FILTER: null,
    LOAD_EVENT_LIST_REQUEST: null,
    LOAD_EVENT_LIST_SUCCESS: null,
    LOAD_EVENT_LIST_FAILURE: null,

    CLEAR_EVENT_NOTE_LIST_ERROR: null,

    CLEAR_EVENT_NOTE_LIST: null,

    CLEAR_EVENT_NOTE_LIST_FILTER: null,
    CHANGE_EVENT_NOTE_LIST_FILTER: null,
    LOAD_EVENT_NOTE_LIST_REQUEST: null,
    LOAD_EVENT_NOTE_LIST_SUCCESS: null,
    LOAD_EVENT_NOTE_LIST_FAILURE: null,

    CLEAR_EVENT_NOTIFICATION_LIST_ERROR: null,

    CLEAR_EVENT_NOTIFICATION_LIST: null,

    CLEAR_EVENT_NOTIFICATION_LIST_FILTER: null,
    CHANGE_EVENT_NOTIFICATION_LIST_FILTER: null,
    LOAD_EVENT_NOTIFICATION_LIST_REQUEST: null,
    LOAD_EVENT_NOTIFICATION_LIST_SUCCESS: null,
    LOAD_EVENT_NOTIFICATION_LIST_FAILURE: null,

    CLEAR_EVENT_COUNT: null,
    CLEAR_EVENT_COUNT_ERROR: null,
    LOAD_EVENT_COUNT_REQUEST: null,
    LOAD_EVENT_COUNT_SUCCESS: null,
    LOAD_EVENT_COUNT_FAILURE: null,

    CLEAR_EVENT_DETAILS: null,
    CLEAR_EVENT_DETAILS_ERROR: null,
    LOAD_EVENT_DETAILS_REQUEST: null,
    LOAD_EVENT_DETAILS_SUCCESS: null,
    LOAD_EVENT_DETAILS_FAILURE: null,

    CLEAR_EVENT_FORM: null,
    CLEAR_EVENT_FORM_ERROR: null,
    CLEAR_EVENT_FORM_FIELD_ERROR: null,

    CHANGE_EVENT_FORM_TAB: null,

    CHANGE_EVENT_FORM_FIELD: null,
    CHANGE_EVENT_FORM_FIELDS: null,

    VALIDATE_EVENT_FORM: null,

    SAVE_EVENT_REQUEST: null,
    SAVE_EVENT_SUCCESS: null,
    SAVE_EVENT_FAILURE: null,

    CLEAR_NOTE_LIST_ERROR: null,

    CLEAR_NOTE_LIST: null,

    CLEAR_NOTE_LIST_FILTER: null,
    CHANGE_NOTE_LIST_FILTER: null,
    LOAD_NOTE_LIST_REQUEST: null,
    LOAD_NOTE_LIST_SUCCESS: null,
    LOAD_NOTE_LIST_FAILURE: null,

    CLEAR_NOTE_HISTORY_ERROR: null,

    CLEAR_NOTE_HISTORY: null,

    LOAD_NOTE_HISTORY_REQUEST: null,
    LOAD_NOTE_HISTORY_SUCCESS: null,
    LOAD_NOTE_HISTORY_FAILURE: null,

    CLEAR_NOTE_COUNT: null,
    CLEAR_NOTE_COUNT_ERROR: null,
    LOAD_NOTE_COUNT_REQUEST: null,
    LOAD_NOTE_COUNT_SUCCESS: null,
    LOAD_NOTE_COUNT_FAILURE: null,

    CLEAR_NOTE_DETAILS: null,
    CLEAR_NOTE_DETAILS_ERROR: null,
    LOAD_NOTE_DETAILS_REQUEST: null,
    LOAD_NOTE_DETAILS_SUCCESS: null,
    LOAD_NOTE_DETAILS_FAILURE: null,

    CLEAR_NOTE_FORM: null,
    CLEAR_NOTE_FORM_ERROR: null,
    CLEAR_NOTE_FORM_FIELD_ERROR: null,

    CHANGE_NOTE_FORM_TAB: null,

    CHANGE_NOTE_FORM_FIELD: null,
    CHANGE_NOTE_FORM_FIELDS: null,

    VALIDATE_NOTE_FORM: null,

    SAVE_NOTE_REQUEST: null,
    SAVE_NOTE_SUCCESS: null,
    SAVE_NOTE_FAILURE: null,

    CLEAR_EVENT_NOTE_COMPOSED_LIST_ERROR: null,

    CLEAR_EVENT_NOTE_COMPOSED_LIST: null,

    CLEAR_EVENT_NOTE_COMPOSED_LIST_FILTER: null,
    CHANGE_EVENT_NOTE_COMPOSED_LIST_FILTER: null,
    LOAD_EVENT_NOTE_COMPOSED_LIST_REQUEST: null,
    LOAD_EVENT_NOTE_COMPOSED_LIST_SUCCESS: null,
    LOAD_EVENT_NOTE_COMPOSED_LIST_FAILURE: null,

    CLEAR_EVENT_NOTE_COMPOSED_COUNT: null,
    CLEAR_EVENT_NOTE_COMPOSED_COUNT_ERROR: null,
    LOAD_EVENT_NOTE_COMPOSED_COUNT_REQUEST: null,
    LOAD_EVENT_NOTE_COMPOSED_COUNT_SUCCESS: null,
    LOAD_EVENT_NOTE_COMPOSED_COUNT_FAILURE: null,

    CLEAR_CLIENT_EVENT_LIST_ERROR: null,

    CLEAR_CLIENT_DOCUMENT_LIST_ERROR: null,

    CLEAR_CLIENT_DOCUMENT_LIST: null,

    CLEAR_CLIENT_DOCUMENT_LIST_FILTER: null,
    CHANGE_CLIENT_DOCUMENT_LIST_FILTER: null,
    LOAD_CLIENT_DOCUMENT_LIST_REQUEST: null,
    LOAD_CLIENT_DOCUMENT_LIST_SUCCESS: null,
    LOAD_CLIENT_DOCUMENT_LIST_FAILURE: null,

    CLEAR_CLIENT_DOCUMENT_COUNT: null,
    CLEAR_CLIENT_DOCUMENT_COUNT_ERROR: null,
    LOAD_CLIENT_DOCUMENT_COUNT_REQUEST: null,
    LOAD_CLIENT_DOCUMENT_COUNT_SUCCESS: null,
    LOAD_CLIENT_DOCUMENT_COUNT_FAILURE: null,

    CLEAR_CLIENT_DOCUMENT_DETAILS: null,
    CLEAR_CLIENT_DOCUMENT_DETAILS_ERROR: null,
    LOAD_CLIENT_DOCUMENT_DETAILS_REQUEST: null,
    LOAD_CLIENT_DOCUMENT_DETAILS_SUCCESS: null,
    LOAD_CLIENT_DOCUMENT_DETAILS_FAILURE: null,

    CLEAR_DELETE_CLIENT_DOCUMENT: null,
    CLEAR_DELETE_CLIENT_DOCUMENT_ERROR: null,
    LOAD_DELETE_CLIENT_DOCUMENT_REQUEST: null,
    LOAD_DELETE_CLIENT_DOCUMENT_SUCCESS: null,
    LOAD_DELETE_CLIENT_DOCUMENT_FAILURE: null,

    CLEAR_CLIENT_DOCUMENT_HISTORY_ERROR: null,

    CLEAR_CLIENT_DOCUMENT_HISTORY: null,

    LOAD_CLIENT_DOCUMENT_HISTORY_REQUEST: null,
    LOAD_CLIENT_DOCUMENT_HISTORY_SUCCESS: null,
    LOAD_CLIENT_DOCUMENT_HISTORY_FAILURE: null,

    CLEAR_CLIENT_DOCUMENT_FORM: null,
    CLEAR_CLIENT_DOCUMENT_FORM_ERROR: null,
    CLEAR_CLIENT_DOCUMENT_FORM_FIELD_ERROR: null,

    CHANGE_CLIENT_DOCUMENT_FORM_FIELD: null,
    CHANGE_CLIENT_DOCUMENT_FORM_FIELDS: null,

    VALIDATE_CLIENT_DOCUMENT_FORM: null,

    SAVE_CLIENT_DOCUMENT_REQUEST: null,
    SAVE_CLIENT_DOCUMENT_SUCCESS: null,
    SAVE_CLIENT_DOCUMENT_FAILURE: null,

    CLEAR_SERVICE_LIST: null,
    LOAD_SERVICE_LIST_SUCCESS: null,
    LOAD_SERVICE_LIST_FAILURE: null,

    CLEAR_INSURANCE_NETWORK_LIST: null,

    CLEAR_INSURANCE_NETWORK_LIST_FILTER: null,
    CHANGE_INSURANCE_NETWORK_LIST_FILTER: null,
    CHANGE_INSURANCE_NETWORK_LIST_FILTER_FIELD: null,

    LOAD_INSURANCE_NETWORK_LIST_REQUEST: null,
    LOAD_INSURANCE_NETWORK_LIST_SUCCESS: null,
    LOAD_INSURANCE_NETWORK_LIST_FAILURE: null,

    CLEAR_DIRECTORY_INSURANCE_NETWORK_LIST: null,

    LOAD_DIRECTORY_INSURANCE_NETWORK_LIST_REQUEST: null,
    LOAD_DIRECTORY_INSURANCE_NETWORK_LIST_SUCCESS: null,
    LOAD_DIRECTORY_INSURANCE_NETWORK_LIST_FAILURE: null,

    CLEAR_INSURANCE_PAYMENT_PLAN_LIST: null,
    LOAD_INSURANCE_PAYMENT_PLAN_LIST_REQUEST: null,
    LOAD_INSURANCE_PAYMENT_PLAN_LIST_SUCCESS: null,
    LOAD_INSURANCE_PAYMENT_PLAN_LIST_FAILURE: null,

    CLEAR_REPORT_GROUP_LIST: null,
    LOAD_REPORT_GROUP_LIST_REQUEST: null,
    LOAD_REPORT_GROUP_LIST_SUCCESS: null,
    LOAD_REPORT_GROUP_LIST_FAILURE: null,

    CLEAR_REPORT_TYPE_LIST: null,
    LOAD_REPORT_TYPE_LIST_REQUEST: null,
    LOAD_REPORT_TYPE_LIST_SUCCESS: null,
    LOAD_REPORT_TYPE_LIST_FAILURE: null,

    CLEAR_REPORT_LIST_ERROR: null,

    CLEAR_REPORT_LIST: null,
    CLEAR_REPORT_LIST_FILTER: null,
    CHANGE_REPORT_LIST_FILTER: null,
    CHANGE_REPORT_LIST_FILTER_FIELD: null,

    LOAD_REPORT_LIST_REQUEST: null,
    LOAD_REPORT_LIST_SUCCESS: null,
    LOAD_REPORT_LIST_FAILURE: null,

    CLEAR_REPORT_DOCUMENT: null,
    CLEAR_REPORT_DOCUMENT_ERROR: null,
    DOWNLOAD_REPORT_DOCUMENT_REQUEST: null,
    DOWNLOAD_REPORT_DOCUMENT_SUCCESS: null,
    DOWNLOAD_REPORT_DOCUMENT_FAILURE: null,

    CLEAR_CAN_ADD_REPORT: null,
    CLEAR_CAN_ADD_REPORT_ERROR: null,
    LOAD_CAN_ADD_REPORT_REQUEST: null,
    LOAD_CAN_ADD_REPORT_SUCCESS: null,
    LOAD_CAN_ADD_REPORT_FAILURE: null,

    CLEAR_CAN_ADD_SERVICE_PLAN: null,
    CLEAR_CAN_ADD_SERVICE_PLAN_ERROR: null,
    LOAD_CAN_ADD_SERVICE_PLAN_REQUEST: null,
    LOAD_CAN_ADD_SERVICE_PLAN_SUCCESS: null,
    LOAD_CAN_ADD_SERVICE_PLAN_FAILURE: null,
})